framework:
#    default_locale: '%locale%'
    default_locale: en
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
#            - '%locale%'
             - en
