twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        avatar_directory: '%avatar_directory%'
        custom_char_card_dir: '%custom_char_card_dir%'
        char_card_dir: '%char_card_dir%'
        util_card_dir: '%util_card_dir%'

