#index:
#    path: /
#    controller: App\Controller\ArticleController::homepage
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /2fa_check